Update ci-cd-gke.yaml

diff --git a/.github/workflows/ci-cd-gke.yaml b/.github/workflows/ci-cd-gke.yaml
--- a/.github/workflows/ci-cd-gke.yaml
+++ b/.github/workflows/ci-cd-gke.yaml
@@ -54,6 +54,15 @@ jobs:
         run: | 
             docker-compose --env-file .env -f docker-compose.yml up -d
             sleep 10 # Allow time for the application to start
+
+      - name: Test the application with curl
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5001)
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Test failed with HTTP status $RESPONSE"
+            exit 1
+          fi
+          echo "Test passed with HTTP status $RESPONSE"            
             
   helm-ci:
     runs-on: ubuntu-latest
@@ -187,6 +196,10 @@ jobs:
             --namespace default \
             --set flaskApp.tag=${IMAGE_TAG}
           helm list
+          
+      - name: Restart Kubernetes Deployment
+        run: |
+          kubectl rollout restart deployment flask-app  
 
       - name: Debug Kubernetes Pods
         run: |
